const assert=require('node:assert/strict');
const {diameters,weights,cdf,emd,cost}=require('../web/math.js');
assert.equal(diameters.length,11);
assert.ok(Math.abs(weights.reduce((a,b)=>a+b,0)-5)<1e-12);
const all=cdf(Array(11).fill(0));
assert.equal(all.curve[10],100);
assert.ok(all.curve.every((v,i)=>!i||v>=all.curve[i-1]));
assert.ok(Math.abs(all.masses.reduce((a,b)=>a+b,0)-100)<1e-10);
assert.equal(emd(all.curve,all.curve).total,0);
assert.equal(emd(Array(11).fill(0),Array(11).fill(100)).total,500);
const a=Array(11).fill(0),b=a.slice();b[0]=10;
assert.ok(Math.abs(emd(a,b).total-10*weights[0])<1e-12);
const high=cdf([10000,...Array(10).fill(-10000)]);
assert.equal(high.curve[10],100);
assert.ok(high.curve.every(Number.isFinite));
const c=cost({epochs:40,steps:50,folds:5,seeds:3,seconds:.5,overhead:30});
assert.equal(c.updates,30000);
assert.ok(Math.abs(c.totalHours-5.416666666666667)<1e-12);
assert.throws(()=>cost({epochs:0,steps:1,folds:1,seeds:1,seconds:1,overhead:0}));
assert.throws(()=>cdf([NaN,...Array(10).fill(0)]));
console.log('Portal numerical checks passed: softmax, monotonicity, EMD units, cost and extreme logits.');
