"""Synchronize the offline portal with repository facts; no CDN or API needed."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import sys
import _bootstrap  # noqa: F401
from phygrainnet.config import load_config
from phygrainnet.constants import DIAMETERS_MM, EMD_WEIGHTS

ROOT = Path(__file__).resolve().parents[1]


def payload():
    profile = json.loads((ROOT / "docs/model_profile.json").read_text(encoding="utf-8"))
    profile["model"].pop("layers", None)
    return {"snapshot_date": "2026-10-10", "status": json.loads((ROOT / "project_status.json").read_text(encoding="utf-8")),
            "config": load_config(ROOT / "configs/phygrainnet/kaggle_scratch.yaml"),
            "profile": profile, "diameters": DIAMETERS_MM.tolist(), "weights": EMD_WEIGHTS.tolist(),
            "ablations": [{"file": f"configs/ablations/{p.name}", "id": load_config(p)["experiment_id"],
                           "description": load_config(p)["notes_short"]}
                          for p in sorted((ROOT / "configs/ablations").glob("*.yaml"))]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = "/* Generated by scripts/build_portal.py. Do not edit by hand. */\nwindow.PROJECT = " + json.dumps(payload(), ensure_ascii=False, indent=2) + ";\n"
    path = ROOT / "web/project-data.js"
    expected = {path: content}
    assets = {name: (ROOT / "web" / name).read_text(encoding="utf-8") for name in ["styles.css", "glossary.js", "math.js", "app.js"]}
    assets["project-data.js"] = content
    for source, destination in [("index.html", "dashboard.html"), ("paper.html", "paper.html")]:
        html = (ROOT / "web" / source).read_text(encoding="utf-8")
        html = html.replace('<link rel="stylesheet" href="styles.css">', '<style>\n' + assets["styles.css"] + '\n</style>')
        for name in ["project-data.js", "glossary.js", "math.js", "app.js"]:
            # Keep defer semantics for inline scripts: execute after DOM parsing.
            script = assets[name]
            html = html.replace(f'<script defer src="{name}"></script>', '')
            html = html.replace('</body>', '<script>\n' + script + '\n</script></body>')
        html = html.replace('href="index.html', 'href="dashboard.html')
        expected[ROOT / "docs" / destination] = html
    if args.check:
        for artifact, contents in expected.items():
            if not artifact.exists() or artifact.read_text(encoding="utf-8") != contents:
                sys.exit(f"Portal stale: {artifact.name}; run scripts/build_portal.py")
        print("Portal snapshot matches status, config, profile and ablations")
    else:
        for artifact, contents in expected.items():
            artifact.parent.mkdir(parents=True, exist_ok=True)
            artifact.write_text(contents, encoding="utf-8")
            print(f"Updated {artifact}")


if __name__ == "__main__":
    main()
