/* Plain-language comments exposed as hover/focus/tap definitions. */
window.GLOSSARY = {
 'GSD':'Grain Size Distribution: distribusi ukuran butiran tanah. Di sini berupa persentase massa kumulatif yang lolos pada 11 diameter saringan.',
 'PSD':'Particle Size Distribution: istilah lain untuk distribusi ukuran partikel; pada proyek ini digunakan setara dengan GSD.',
 'CDF':'Cumulative Distribution Function: fungsi kumulatif. F(d)=persentase massa butiran berdiameter ≤ d; selalu naik atau tetap.',
 'PPM':'Pixels per millimetre (px/mm), jumlah piksel yang mewakili satu milimeter fisik. Bukan parts per million dalam proyek ini.',
 'tile':'Potongan kecil dari foto. Beberapa tile dari beberapa foto tetap mewakili satu sampel tanah dan satu label.',
 'multi-view':'Menggabungkan bukti dari beberapa foto sampel yang sama. Foto-foto tersebut bukan sampel berlabel independen.',
 'multi-scale':'Melihat pusat tanah yang sama dengan dua luas bidang: 25,6 mm untuk tekstur detail dan 102,4 mm untuk konteks.',
 'domain shift':'Perubahan kondisi antara data latih dan data uji, misalnya kamera Motorola/Samsung menjadi iPhone dan lokasi tanah baru.',
 'gray-world':'White balance yang mengasumsikan rata-rata warna scene mendekati abu-abu. Bisa mengurangi bias kamera, tetapi manfaatnya harus diuji.',
 'Sobel':'Filter tetap untuk menghitung perubahan intensitas arah horizontal/vertikal. Magnitudonya menonjolkan batas dan tekstur butiran.',
 'Laplacian':'Filter turunan kedua intensitas. Menonjolkan perubahan lokal tajam; sensitif terhadap noise dan blur.',
 'CNN':'Convolutional Neural Network: jaringan yang mempelajari pola spasial melalui filter konvolusi pada gambar.',
 'depthwise':'Konvolusi terpisah per kanal. Biaya kira-kira H×W×k²×C, lebih murah daripada mencampur semua kanal dengan kernel yang sama.',
 'dilated':'Konvolusi dengan jarak antar titik kernel; melihat konteks lebih luas tanpa menambah ukuran kernel 3×3.',
 'GroupNorm':'Normalisasi fitur dalam kelompok kanal per contoh, sehingga tidak bergantung pada ukuran batch. Cocok untuk batch kecil.',
 'GELU':'Gaussian Error Linear Unit: fungsi aktivasi nonlinear yang mengatur lewatnya nilai fitur secara halus.',
 'attention pooling':'Memberi bobot terpelajar pada tile saat menggabungkannya. Di sini attention linear atas tile, bukan self-attention kuadratik seperti Transformer.',
 'embedding':'Vektor angka ringkas yang mewakili pola dari gambar atau sampel; tidak mempunyai satuan diameter langsung.',
 'softmax':'Mengubah logit menjadi proporsi positif dengan total satu. Setelah dikali 100, menghasilkan massa interval yang totalnya 100%.',
 'logit':'Skor mentah keluaran jaringan sebelum softmax. Logit boleh negatif; massa dan kurva hasilnya tetap nonnegatif.',
 'cumsum':'Cumulative sum: penjumlahan massa interval dari kecil ke besar untuk membentuk CDF yang monoton.',
 'EMD':'Earth Mover’s Distance versi kompetisi: jumlah selisih absolut CDF dalam poin persentase × lebar interval log10 diameter. Lebih rendah lebih baik; rentang teoritis 0–500.',
 'OOF':'Out-of-fold: prediksi sebuah sampel dibuat oleh model yang tidak dilatih pada sampel atau kelompoknya. Digunakan untuk evaluasi lokal.',
 'grouped CV':'Cross-validation dengan seluruh sampel dari kelompok lokasi yang sama disimpan dalam satu fold; mengurangi kebocoran data.',
 'fold':'Satu pembagian data latih/validasi. Lima fold menghasilkan lima model dan setiap sampel mendapat satu prediksi OOF.',
 'leakage':'Kebocoran informasi validasi ke pelatihan atau pemilihan model, sehingga skor lokal menjadi terlalu optimistis.',
 'ablation':'Eksperimen terkontrol yang menghilangkan satu komponen untuk menguji apakah komponen itu benar-benar membantu.',
 'AdamW':'Optimizer berbasis momentum dan adaptasi langkah dengan weight decay terpisah. Memperbarui bobot untuk menurunkan loss.',
 'epoch':'Satu periode pelatihan. Di proyek ini panjangnya ditentukan steps_per_epoch, bukan satu kali melewati semua foto.',
 'batch':'Sekelompok sampel tanah dalam satu pembaruan model. Profil Kaggle: B=2; masing-masing memiliki T=6 tile dan S=2 skala.',
 'learning rate':'Besar langkah pembaruan bobot optimizer. Nilai awal 0,001, lalu warm-up dan cosine decay.',
 'weight decay':'Regularisasi yang menekan besarnya bobot. AdamW menggunakan 0,05 dalam konfigurasi awal.',
 'EMA':'Exponential Moving Average: rata-rata bergerak bobot model (decay 0,995). Bobot EMA dipakai untuk prediksi akhir.',
 'AMP':'Automatic Mixed Precision: sebagian operasi memakai FP16 di CUDA untuk menghemat memori dan dapat mempercepat pelatihan. Loss tetap FP32.',
 'gradient clipping':'Membatasi norma gradien maksimum (1,0) untuk mengurangi lonjakan pembaruan yang tidak stabil.',
 'TTA':'Test-Time Augmentation: prediksi pada rotasi/flip gambar lalu dirata-ratakan. TTA=4 berarti empat rotasi.',
 'SSL':'Self-supervised learning: mempelajari representasi dari foto tanpa label laboratorium. Tidak menjadikan foto uji mempunyai label.',
 'SimCLR':'Metode SSL yang mendekatkan representasi dua augmentasi foto yang sama dan memisahkan foto berbeda melalui contrastive loss.',
 'transductive':'Protokol yang memanfaatkan foto tanpa label dari data validasi/uji saat pretraining. Harus dilaporkan terpisah dari evaluasi induktif.',
 'inductive':'Evaluasi di mana data validasi/uji, termasuk foto tanpa labelnya, tidak dipakai untuk pelatihan representasi.',
 'ETS':'École de technologie supérieure, Montréal. Dataset kandidat: 321 sampel, 12.714 foto; domain dan cakupan label berbeda dari kompetisi.',
 'masked loss':'Loss yang hanya menghitung titik diameter dengan label tersedia. Titik ETS <0,08 mm tidak dianggap mempunyai label.',
 'hinge':'Penalti max(0, prediksi−batas). Dipakai agar passing pada titik halus yang tanpa label tidak melebihi passing saringan 0,08 mm.',
 'D50':'Diameter saat CDF mencapai 50% massa. Interpolasi pada log10 diameter; tidak diekstrapolasi di bawah 0,002 mm.',
 'D10':'Diameter saat 10% massa telah lolos; bisa berada di bawah titik dukungan sehingga nilainya dilaporkan tidak terdefinisi.',
 'bootstrap':'Estimasi variasi statistik dengan mengambil ulang kelompok lokasi, dengan pengembalian. Interval ini tidak mencakup bias pemilihan model.',
 'Big O':'Notasi laju pertumbuhan biaya terhadap ukuran input. Tidak memberi waktu detik; konstanta, GPU, data loader, dan implementasi tetap menentukan.',
 'MAC':'Multiply–accumulate: satu perkalian dan penjumlahan. Profil hanya menghitung Conv2d dan Linear; kira-kira dua FLOP per MAC.',
 'FLOP':'Floating-point operation: satu operasi aritmetika. Angka estimasi ini bukan pengukuran throughput GPU atau semua operasi program.',
 'VRAM':'Memori pada GPU. Dua T4 tidak otomatis menjadi satu memori gabungan; kode sekarang memakai cuda:0.',
 'CUDA':'Platform komputasi NVIDIA yang memungkinkan PyTorch menjalankan operasi pada GPU yang kompatibel.',
 'DDP':'DistributedDataParallel: pelatihan multi-GPU yang harus diimplementasikan secara eksplisit. Belum digunakan di proyek ini.',
 'checkpoint':'Berkas bobot model beserta konfigurasi dan asal bobot. Saat ini untuk pemulihan inferensi; optimizer tidak disimpan untuk resume epoch.',
 'ridge':'Regresi linear dengan regularisasi L2; cocok sebagai pembanding pada sedikit sampel dan fitur fisik buatan.',
 'CLR':'Centered log-ratio: transformasi log massa interval relatif terhadap rata-rata geometrik, untuk regresi data komposisi.',
 'PLS':'Partial Least Squares: regresi melalui komponen laten yang menghubungkan fitur dan target.',
 'LBP':'Local Binary Pattern: ringkasan pola perbandingan intensitas tetangga piksel untuk tekstur.',
 'granulometry':'Pengukuran respons tekstur terhadap struktur morfologi berbagai ukuran; fitur ukuran dikalibrasi dalam mm.',
 'Fourier':'Transformasi gambar ke frekuensi spasial. Energi per panjang gelombang membantu merangkum ukuran pola tekstur.',
 'ensemble':'Menggabungkan beberapa model. Median per titik dihitung untuk mempertahankan kurva monoton; manfaatnya diuji lewat OOF.',
 'private leaderboard':'Peringkat pada bagian label uji tersembunyi. Target kompetisi; tidak dapat disimpulkan dari tes lokal atau tiga sampel public leaderboard.',
 'hyperparameter':'Pengaturan sebelum training, seperti learning rate, epoch, batch dan jumlah tile; berbeda dari bobot yang dipelajari model.'
};
Object.assign(window.GLOSSARY, {
 'encoder':'Bagian jaringan yang mengubah gambar menjadi vektor fitur; bobotnya dipelajari dari training, bukan aturan diameter langsung.',
 'inference':'Menjalankan model yang sudah dilatih pada foto baru untuk menghasilkan prediksi; tidak memperbarui bobot dan tidak memerlukan label.',
 'preprocessing':'Transformasi sebelum model: membaca foto, crop border, kalibrasi ukuran fisik, serta normalisasi warna.',
 'MLP':'Multilayer Perceptron: jaringan linear dan aktivasi berlapis yang memproses vektor fitur, bukan grid gambar.',
 'LayerNorm':'Normalisasi vektor fitur satu contoh pada dimensi embedding. Berbeda dari GroupNorm yang mengelompokkan kanal spasial.',
 'stride':'Jarak pergeseran kernel konvolusi. Stride 2 mengecilkan tinggi dan lebar fitur kira-kira separuh.',
 'gate':'Bobot 0–1 per kanal untuk mengatur pengaruh fitur. Dipelajari oleh jaringan kecil dari rata-rata spasial fitur.',
 'residual':'Koneksi yang menambahkan input ke hasil transformasinya. Membantu aliran gradien pada jaringan.',
 'FP16':'Floating point 16 bit. Mengurangi kebutuhan memori per angka dibanding FP32, tetapi memiliki rentang dan ketelitian lebih kecil.',
 'FP32':'Floating point 32 bit. Digunakan untuk bobot dan loss; satu angka memerlukan empat byte.',
 'random init':'Bobot awal diambil dari distribusi acak, tanpa memakai model gambar yang telah dilatih pihak lain.',
 'baseline':'Metode pembanding sederhana. Model baru perlu lebih baik pada protokol validasi identik, bukan hanya menghasilkan prediksi.',
 'warm-up':'Fase awal peningkatan learning rate secara bertahap untuk menstabilkan training.',
 'cosine':'Jadwal learning rate yang menurun mengikuti fungsi cosinus setelah warm-up.',
 'dropout':'Regularisasi dengan menonaktifkan fitur acak saat training. Dinonaktifkan saat inference.',
 'mask':'Penanda biner untuk membedakan data valid dan padding, atau label tersedia dan label tidak tersedia.',
 'OOF EMD':'Skor EMD atas prediksi out-of-fold. Setiap sampel diprediksi model yang tidak melihat label maupun kelompoknya saat training.',
 'censored':'Nilai di luar jangkauan pengukuran yang tersedia; dilaporkan tidak terdefinisi, tidak ditebak melalui extrapolation.',
 'D30':'Diameter pada 30% massa lolos, dihitung lewat inverse CDF log-linear jika berada dalam dukungan.',
 'D60':'Diameter pada 60% massa lolos. Bersama D10 dapat dipakai untuk koefisien uniformitas Cu bila keduanya valid.',
 'MAE':'Mean Absolute Error: rata-rata selisih absolut prediksi dan target. Satuan mengikuti target, misalnya poin persentase atau mm.',
 'CI95':'Interval kepercayaan 95% menurut prosedur bootstrap yang ditentukan. Tidak berarti 95% semua prediksi individu benar.',
 'OOF lengkap':'Setiap sampel memiliki tepat satu prediksi validasi, seluruh fold selesai, dan tidak ada kelompok bocor ke training.',
 'hyperparameters':'Pengaturan training/model sebelum belajar: epoch, batch, learning rate dan tile. Sama dengan hyperparameter.',
 'FFT':'Fast Fourier Transform: algoritme untuk menghitung transformasi Fourier dengan biaya O(M log M) pada M piksel.',
 'MiB':'Mebibyte: 2²⁰ byte. Berbeda dari MB desimal 10⁶ byte.',
 'GMAC':'Satu miliar multiply–accumulate. Profil proyek hanya menghitung modul Conv2d dan Linear.',
 'GAP':'Global Average Pooling: merata-ratakan fitur pada seluruh posisi spasial menjadi satu angka per kanal.',
 'GN':'Singkatan GroupNorm; normalisasi per kelompok kanal, bukan per batch.',
 'DW':'Singkatan depthwise convolution; filter per kanal sebelum pencampuran 1×1.',
 'CLRRegressor':'Regresi target distribusi dalam koordinat centered log-ratio massa; inverse softmax menghasilkan proporsi valid.',
 'kNN':'k-nearest neighbors: memprediksi dari k sampel latih yang fiturnya paling dekat dengan sampel baru.',
 'full fit':'Melatih model tambahan memakai seluruh label train setelah cross-validation; menambah biaya dan bukan sumber skor OOF.',
 'channel':'Kanal fitur gambar. RGB mempunyai tiga kanal; texture stream menambah dua kanal analitik.',
 'std':'Standard deviation: simpangan baku. Menggambarkan keragaman fitur, bukan ketidakpastian prediksi yang terkalibrasi.'
});
