/* Generated by scripts/build_portal.py. Do not edit by hand. */
window.PROJECT = {
  "snapshot_date": "2026-10-10",
  "status": {
    "project": "PhyGrainNet",
    "overall_progress_percent": 10,
    "competition_readiness_percent": 10,
    "current_phase": "P2",
    "current_phase_name": "Dataset Audit (code ready, Kaggle run pending)",
    "next_phase": "P5",
    "next_phase_name": "Baselines + first submission",
    "default_seed": 42,
    "primary_environment": "Kaggle Notebook / Kaggle IDE",
    "best_local_cv_emd": null,
    "best_public_score": null,
    "gates": {
      "G0": {
        "name": "Research Specification",
        "status": "passed",
        "completion": 1.0
      },
      "G1": {
        "name": "Data Integrity",
        "status": "blocked",
        "completion": 0
      },
      "G2": {
        "name": "Experimental Validity",
        "status": "in_progress",
        "completion": 0.5
      },
      "G3": {
        "name": "Architecture Validation",
        "status": "blocked",
        "completion": 0
      },
      "G4": {
        "name": "Competition Ready",
        "status": "blocked",
        "completion": 0
      },
      "G5": {
        "name": "Research Ready",
        "status": "blocked",
        "completion": 0
      }
    },
    "phases": [
      {
        "id": "P0",
        "name": "Research specification",
        "cumulative_progress": 4,
        "status": "complete"
      },
      {
        "id": "P1",
        "name": "Repository foundation",
        "cumulative_progress": 8,
        "status": "complete"
      },
      {
        "id": "P2",
        "name": "Dataset audit",
        "cumulative_progress": 14,
        "status": "in_progress"
      },
      {
        "id": "P3",
        "name": "EDA",
        "cumulative_progress": 20,
        "status": "code_ready"
      },
      {
        "id": "P4",
        "name": "Exact metric + leakage-safe CV",
        "cumulative_progress": 28,
        "status": "code_ready"
      },
      {
        "id": "P5",
        "name": "Baselines",
        "cumulative_progress": 38,
        "status": "code_ready"
      },
      {
        "id": "P6",
        "name": "PhyGrainNet v0",
        "cumulative_progress": 50,
        "status": "pending"
      },
      {
        "id": "P7",
        "name": "Physical multi-scale modelling",
        "cumulative_progress": 60,
        "status": "pending"
      },
      {
        "id": "P8",
        "name": "Texture + multi-view modelling",
        "cumulative_progress": 70,
        "status": "pending"
      },
      {
        "id": "P9",
        "name": "Ablation study",
        "cumulative_progress": 80,
        "status": "pending"
      },
      {
        "id": "P10",
        "name": "Robust evaluation",
        "cumulative_progress": 87,
        "status": "pending"
      },
      {
        "id": "P11",
        "name": "Ensemble + Kaggle submission",
        "cumulative_progress": 92,
        "status": "pending"
      },
      {
        "id": "P12",
        "name": "Error analysis",
        "cumulative_progress": 96,
        "status": "pending"
      },
      {
        "id": "P13",
        "name": "Reproducibility packaging",
        "cumulative_progress": 98,
        "status": "pending"
      },
      {
        "id": "P14",
        "name": "Paper-ready evidence",
        "cumulative_progress": 100,
        "status": "pending"
      }
    ],
    "deadline": "2026-11-30 18:00 WIB",
    "goal": "private leaderboard with models trained from random init; public soil data allowed for pretraining",
    "software_release": {
      "version": "0.3.0",
      "completion_percent": 100,
      "scope": "Local development release: pipeline tools, interactive dashboard and methods paper. This is separate from scientific/competition completion.",
      "checklist": [
        {
          "id": "core_pipeline",
          "complete": true
        },
        {
          "id": "model_invariants",
          "complete": true
        },
        {
          "id": "compute_profiler",
          "complete": true
        },
        {
          "id": "geotechnical_report",
          "complete": true
        },
        {
          "id": "ablation_configs",
          "complete": true
        },
        {
          "id": "dashboard",
          "complete": true
        },
        {
          "id": "methods_paper",
          "complete": true
        },
        {
          "id": "kaggle_runner",
          "complete": true
        },
        {
          "id": "offline_snapshot",
          "complete": true
        },
        {
          "id": "verification",
          "complete": true
        }
      ],
      "verification": "docs/LOCAL_VERIFICATION.md",
      "research_limit": "No real Kaggle dataset/CUDA run, complete competition OOF, ablation evidence or leaderboard result in this workspace."
    },
    "updated_at": "2026-10-10"
  },
  "config": {
    "project": "PhyGrainNet",
    "seed": 42,
    "pipeline": "cnn",
    "data": {
      "root": "/kaggle/input/soil-grain-size-from-photos",
      "cache_dir": "/kaggle/working/cache",
      "scale_mode": "resize",
      "target_ppm": 10.0,
      "border_frac": 0.06,
      "color_mode": "grayworld",
      "fields_mm": [
        25.6,
        102.4
      ],
      "tile_px": 256,
      "num_workers": 2,
      "n_jobs": 2,
      "strict_catalog": true
    },
    "cv": {
      "strategy": "group_kfold",
      "n_folds": 5,
      "max_gap": 10
    },
    "model": {
      "name": "phygrainnet_mv",
      "pretrained": false,
      "channels": [
        32,
        48,
        96,
        160,
        224
      ],
      "blocks": [
        1,
        2,
        2,
        3,
        2
      ],
      "texture_stream": true,
      "share_scales": true,
      "embed_dim": 256,
      "dropout": 0.2
    },
    "training": {
      "epochs": 40,
      "steps_per_epoch": 50,
      "batch_size": 2,
      "tiles_per_sample": 6,
      "learning_rate": 0.001,
      "weight_decay": 0.05,
      "warmup_steps": 200,
      "gradient_clip_norm": 1.0,
      "ema_decay": 0.995,
      "mix_prob": 0.3,
      "scale_jitter": 0.08,
      "photometric": 1.0,
      "bound_weight": 1.0,
      "eval_every": 10,
      "amp": true,
      "full_fit": false,
      "init_checkpoint": null,
      "init_encoder_only": false
    },
    "inference": {
      "tta": 4,
      "max_tiles_per_image": 48,
      "chunk": 16
    },
    "output": {
      "dir": "/kaggle/working/outputs",
      "registry": "/kaggle/working/registry.csv",
      "save_checkpoints": true
    },
    "experiment_id": "C100",
    "notes_short": "multi-scale 25.6+102.4mm, texture stream, attention view pooling, random init"
  },
  "profile": {
    "config": {
      "project": "PhyGrainNet",
      "seed": 42,
      "pipeline": "cnn",
      "data": {
        "root": "/kaggle/input/soil-grain-size-from-photos",
        "cache_dir": "/kaggle/working/cache",
        "scale_mode": "resize",
        "target_ppm": 10.0,
        "border_frac": 0.06,
        "color_mode": "grayworld",
        "fields_mm": [
          25.6,
          102.4
        ],
        "tile_px": 256,
        "num_workers": 2,
        "n_jobs": 2,
        "strict_catalog": true
      },
      "cv": {
        "strategy": "group_kfold",
        "n_folds": 5,
        "max_gap": 10
      },
      "model": {
        "name": "phygrainnet_mv",
        "pretrained": false,
        "channels": [
          32,
          48,
          96,
          160,
          224
        ],
        "blocks": [
          1,
          2,
          2,
          3,
          2
        ],
        "texture_stream": true,
        "share_scales": true,
        "embed_dim": 256,
        "dropout": 0.2
      },
      "training": {
        "epochs": 40,
        "steps_per_epoch": 50,
        "batch_size": 2,
        "tiles_per_sample": 6,
        "learning_rate": 0.001,
        "weight_decay": 0.05,
        "warmup_steps": 200,
        "gradient_clip_norm": 1.0,
        "ema_decay": 0.995,
        "mix_prob": 0.3,
        "scale_jitter": 0.08,
        "photometric": 1.0,
        "bound_weight": 1.0,
        "eval_every": 10,
        "amp": true,
        "full_fit": false,
        "init_checkpoint": null,
        "init_encoder_only": false
      },
      "inference": {
        "tta": 4,
        "max_tiles_per_image": 48,
        "chunk": 16
      },
      "output": {
        "dir": "/kaggle/working/outputs",
        "registry": "/kaggle/working/registry.csv",
        "save_checkpoints": true
      },
      "experiment_id": "C100",
      "notes_short": "multi-scale 25.6+102.4mm, texture stream, attention view pooling, random init"
    },
    "hardware": {
      "python": "3.13.15",
      "torch": "2.13.0+cpu",
      "cuda_available": false,
      "cuda_runtime": null,
      "cudnn": null,
      "cpu_threads": 2,
      "gpus": [],
      "execution": "single GPU (cuda:0) or CPU; no DDP; GPU memory is not pooled"
    },
    "model": {
      "kind": "analytical counts observed on synthetic tensors",
      "input_shape": [
        2,
        6,
        2,
        3,
        256,
        256
      ],
      "parameters": 1518836,
      "trainable_parameters": 1518836,
      "weight_mib_fp32": 5.7938995361328125,
      "adamw_plus_ema_state_mib_fp32": 28.969497680664062,
      "state_memory_note": "5 FP32 arrays: weights, gradients, Adam m/v, EMA; excludes activations, buffers, allocator, AMP temporaries",
      "input_mib_fp32": 18.0,
      "forward_macs_batch": 9717806080,
      "forward_flops_approx_batch": 19435612160,
      "forward_macs_sample": 4858903040,
      "output_shape": [
        2,
        11
      ],
      "count_excludes": "functional texture filters, normalization, activations, pooling, backward, optimizer, IO"
    }
  },
  "diameters": [
    0.002,
    0.0063,
    0.02,
    0.063,
    0.2,
    0.63,
    2.0,
    6.3,
    20.0,
    63.0,
    200.0
  ],
  "weights": [
    0.49831055378960043,
    0.5016894462103996,
    0.49831055378960043,
    0.5016894462103996,
    0.49831055378960043,
    0.5016894462103995,
    0.4983105537896005,
    0.5016894462103996,
    0.49831055378960043,
    0.5016894462103996
  ],
  "ablations": [
    {
      "file": "configs/ablations/mean_pool.yaml",
      "id": "F107",
      "description": "replace attention statistic with mean; retain output dimension"
    },
    {
      "file": "configs/ablations/no_color.yaml",
      "id": "F105",
      "description": "without gray-world white balance"
    },
    {
      "file": "configs/ablations/no_mixing.yaml",
      "id": "F104",
      "description": "without virtual tile mixing"
    },
    {
      "file": "configs/ablations/no_scale_calibration.yaml",
      "id": "F106",
      "description": "native pixels; fields not calibrated to mm"
    },
    {
      "file": "configs/ablations/no_texture.yaml",
      "id": "F101",
      "description": "texture_stream=false; matched C100"
    },
    {
      "file": "configs/ablations/single_scale.yaml",
      "id": "F102",
      "description": "one physical scale; report compute difference"
    },
    {
      "file": "configs/ablations/single_tile.yaml",
      "id": "F103",
      "description": "one tile per sample; reduced evidence and compute"
    }
  ]
};
